FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# Установка библиотек
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir openai-whisper pydub xgboost pandas scikit-learn nltk audiomentations joblib

# Загрузка языковых пакетов nltk
RUN python -m nltk.downloader punkt

# Создаем папку для кэша Whisper
ENV XDG_CACHE_HOME=/root/.cache

COPY ./training /app/training
COPY ./conversations /app/conversations

CMD ["python", "training/train_call_model.py"]

